version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - ./config:/config
    environment:
      TZ: Europe/Zurich
