---
version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=27
      - TZ=Europe/Zurich
      - AUTO_UPDATE=true
    volumes:
      - ./jackett:/config
      - /mnt:/mnt
    ports:
      - 9117:9117
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=27
      - TZ=Europe/Zurich
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=27
      - TZ=Europe/Zurich
    volumes:
      - ./radarr:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=27
      - TZ=Europe/Zurich
    volumes:
      - ./sonarr:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    ports:
      - 5055:5055
    volumes:
      - ./overseerr:/app/config

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ./chinesesubfinder:/config
      - /mnt:/mnt
    environment:
      - PUID=1000
      - PGID=27
      - TZ=Europe/Zurich
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - 8191:8191