---
version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - AUTO_UPDATE=true
    volumes:
      - ./jackett_config:/config
      - ./jackett_downloads:/downloads
    ports:
      - 9117:9117
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./radarr_config:/config
      - ./radarr_movies:/movies #optional
      - ./radarr_downloads:/downloads #optional
    ports:
      - 7878:7878
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr_config:/config
      - ./sonarr_tv:/tv #optional
      - ./sonarr_downloads:/downloads #optional
    ports:
      - 8989:8989